---

- hosts: all
  become: yes

  pre_tasks:

    - name: install updates (rocky)
      tags: always 
      ansible.builtin.dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Rocky"

    - name: install updates (ubuntu)
      tags: always
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
      changed_when: false 
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: yes
  roles: 
    - base


- hosts: workstation
  become: yes
  roles: 
    - workstation 

- hosts: web_server
  become: yes 
  roles:
    - web_server 

- hosts: db_server
  become: yes
  roles:
    - db_server

- hosts: file_server
  become: yes
  roles:
    - file_server


