 - name: add ssh key
   tags: always
   ansible.posix.authorized_key:
     user: simone
     key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII1lycjr7QEMbPBgK3QspKyl0CBTOsz3Y7Fj46eoxU6a shashi key"

 - name: generate sshd config file from template  
   tags: ssh 
   template: 
     src: "{{ ssh_template_file }}"
     dest: /etc/ssh/sshd_config 
     owner: root
     group: root
     mode: 0644
   notify: restart_sshd

